### ISSUE TITLE
Infinite loop and memory leak when flattening a segment that contains one or more NaN points

### ISSUE THREAD

**Issue by Fincap** [aslpavel/rasterize#11]
If any point in a Segment is NaN, then during rasterization the PathFlattenIter will get stuck in an infinite loop of splitting itself pushing both halves onto the Segment stack (which also contain NaN values). Memory usage will rapidly climb and cause severe degradation to the entire computer's performance if the process isn't killed in time.

The infinite loop occurs in this section of `path.rs`: https://github.com/aslpavel/rasterize/blob/f4196d7fba4a106a2c178b8b88947eacb160a2ca/src/path.rs#L664-L672 

Because `f64::NAN` always returns false from comparisons, this loop will never break.

## Steps to reproduce
(I would highly recommend having your finger on the trigger to kill the process since this caused roughly 400MB/s to leak on my machine)
1. Modify `examples/simple.rs` so that any of the coordinates in `squirrel_path` are `f64::NAN`.
2. `cargo run --example=simple`

**Comment by aslpavel** [comment]
Thank you! Merged
