### ISSUE TITLE
Upgrading after the pipeline changes

### ISSUE THREAD

**Issue by lnicola** [aslpavel/rasterize#8]
Hi! Sorry for the support question but I have some code that renders stuff onto multiple `Scene`s, but with the same `transform` and `bbox`. This worked in `0.1`, but broke in `0.2`. One difference I noticed is that the returned `Layer` size was the same for each `Scene`, but now it's different, even `(0, 0)` at times.

Is it possible to get the old behaviour in `0.2`? I _think_ the output shape was determined by the `bbox` and `transform`.

**Comment by aslpavel** [comment]
Sorry for the delayed response, but could you please provide an example of the scene

**Comment by lnicola** [comment]
I can't (easily), but the relevant code is https://github.com/lnicola/walker/blob/master/src/main.rs#L237-L256.

**Comment by aslpavel** [comment]
Could you please test the latest version `0.2.2` and see if it has fixed the issue?

**Comment by lnicola** [comment]
Thanks for looking into it. It almost works, but it's still diverging from 0.1 at one point:

```
# 0.1
[src/main.rs:248] &scene = Stroke {
    path: Line 2.911e6,5.524e6 2.911e6,5.524e6
    Line 2.911e6,5.524e6 2.911e6,5.524e6
    Line 2.911e6,5.524e6 2.911e6,5.524e6
    End
    ,
    paint: LinColor(
        [
            1.0,
            0.11697067,
            0.0056053917,
            1.0,
        ],
    ),
    style: StrokeStyle {
        width: 20.0,
        line_join: Round,
        line_cap: Butt,
    },
}
[src/main.rs:255] &layer = Layer {
    image: ImageOwned {
        shape: Shape {
            width: 882,
            height: 632,
            row_stride: 882,
            col_stride: 1,
        },
        dtype: "rasterize::color::LinColor",
        ..
    },
    x: 363456,
    y: -690725,
}

# 0.2.2
[src/main.rs:248] &scene = Stroke {
    style: StrokeStyle {
        width: 20.0,
        line_join: Round,
        line_cap: Butt,
    },
    paint: LinColor(
        [
            1.0,
            0.11697067,
            0.0056053917,
            1.0,
        ],
    ),
    path: Line 2.911e6,5.524e6 2.911e6,5.524e6
    Line 2.911e6,5.524e6 2.911e6,5.524e6
    Line 2.911e6,5.524e6 2.911e6,5.524e6
    End
    ,
}
[src/main.rs:255] &layer = Layer {
    x: 0,
    y: 0,
    w: 0,
    h: 0,
}
```

**Comment by lnicola** [comment]
This one's on me, I suppose. The path has three lines of length 0 (and the same coordinates).

**Comment by aslpavel** [comment]
I think new implementation tries to throw away layers that do not produce any output when bounding box is empty, this might explain this. Should we close this issue or are there any other problems?

**Comment by lnicola** [comment]
If it's intentional, yes, I can work around it on my side.

(if you were wondering, I've used your crate [for this](https://blog.dend.ro/mapping-my-walks-osrm-rust/)).
